# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: QRL Docs
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Quantum Resistant Ledger
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
collections:
  docs:
    permalink: "/:path/"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs 
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-analytics

#jekyll_analytics:
#  GoogleAnalytics:          # Add, if you want to track with Google Analytics
#    id:           # Required - replace with your tracking id
#    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

url: "https://docs.theqrl.org" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
